export const currencyByRupee: Currency[] = [
  {
    name: 'DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.01125809,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.0099194378,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 0.85040469,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.01732574,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.016457908,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 1.5909089,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.0037446993,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000543544886,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'SWISS FRANC',
    value: 0.010976073,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 0.016305573,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 0.096014225,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'CHINESE YUAN',
    value: 0.08902183,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: 'UAE DIRHAM',
    value: 0.045068635,
    flag: '🇦🇪',
    symbol: 'AED',
  },
  {
    name: 'SAUDI RIYAL',
    value: 0.04604995,
    flag: '🇸🇦',
    symbol: 'SAR',
  },
  {
    name: 'SOUTH KOREAN WON',
    value: 16.276736,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'INDONESIAN RUPIAH',
    value: 184.43954,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'BRAZILIAN REAL',
    value: 0.061517785,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'SOUTH AFRICAN RAND',
    value: 0.22971904,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'MALAYSIAN RINGGIT',
    value: 0.0564845,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'THAI BAHT',
    value: 0.42915727,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'EGYPTIAN POUND',
    value: 0.37735849,
    flag: '🇪🇬',
    symbol: 'E£',
  },
  {
    name: 'PHILIPPINE PESO',
    value: 0.6731598,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'VIETNAMESE DONG',
    value: 288.816,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'TURKISH LIRA',
    value: 0.23456789,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'BANGLADESHI TAKA',
    value: 1.034736,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'PAKISTANI RUPEE',
    value: 3.5294118,
    flag: '🇵🇰',
    symbol: '₨',
  },
  {
    name: 'ARGENTINIAN PESO',
    value: 2.3170732,
    flag: '🇦🇷',
    symbol: 'ARS',
  },
  {
    name: 'CHILEAN PESO',
    value: 10.10101,
    flag: '🇨🇱',
    symbol: 'CLP',
  },
  {
    name: 'NORWEGIAN KRONE',
    value: 0.12865497,
    flag: '🇳🇴',
    symbol: 'kr',
  },
];
